apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowebapp-deployment
  namespace: gowebapp
  labels:
    app: goweb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goweb
  template:
    metadata:
      labels:
        app: goweb
    spec:
      containers:
        - name: goweb-container
          image: marijahmed/gowebapp:{{ .Values.image.tag }}
