apiVersion: v1
kind: Service
metadata:
  name: gowebapp-service
  namespace: gowebapp
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"default": "gowebapp-backendconfig"}'
spec:
  selector:
    app: goweb
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
