on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**"
      - "helm/gowebapp/values.yaml"
      - "**.md"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  static-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
      - name: setup linter
        uses: golangci/golangci-lint-action@v8.0.0

  build:
    runs-on: ubuntu-latest
    needs: static-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: |
          docker build -t marijahmed/gowebapp:${{ github.run_id}} .

      - name: Docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push marijahmed/gowebapp:${{ github.run_id }}

  update-helm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Helm values.yaml
        run: |
          sed -i "s/tag: \".*\"/tag: \"${{ github.run_id }}\"/" helm/gowebapp/values.yaml

      - name: Commit changes
        run: |
          git config --local user.email "muhammadmarijahmed@gmail.com"
          git config --local user.name "marijahmedd"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add helm/gowebapp/values.yaml
          git commit -m "Update Helm chart to use image tag ${{ github.run_id }}"
          git push origin main
