on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**"
      - "helm/gowebapp/values.yaml"
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
      - name: setup linter
        uses: golangci/golangci-lint-action@v8.0.0

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build docker image
        run: |
          docker build -t marijahmed/gowebapp:${{ github.run_id}} .

      - name: Docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push marijahmed/gowebapp:${{ github.run_id }}
